package output

import (
	"fmt"
	"os"
	"regexp"
	"time"

	"printcode2llm/internal/config"
	"printcode2llm/internal/generator"
)

func CleanOldFiles(prefix string) error {
	pattern := fmt.Sprintf("^%s.*\\.md$", regexp.QuoteMeta(prefix))
	re, err := regexp.Compile(pattern)
	if err != nil {
		return err
	}

	entries, err := os.ReadDir(".")
	if err != nil {
		return err
	}

	cleaned := 0
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		if re.MatchString(entry.Name()) {
			if err := os.Remove(entry.Name()); err != nil {
				return fmt.Errorf("删除文件失败 %s: %w", entry.Name(), err)
			}
			cleaned++
		}
	}

	if cleaned > 0 {
		fmt.Printf("  已清理 %d 个旧输出文件\n", cleaned)
	}

	return nil
}

func WriteResults(results []*generator.Result, cfg *config.Config) (int64, error) {
	var totalSize int64

	for resultIdx, result := range results {
		for segIdx, segment := range result.Segments {
			fileName := generateFileName(cfg.Output.OutputPrefix, resultIdx, segIdx, len(results), len(result.Segments))

			content := generateMetaComment(result, segIdx+1, len(result.Segments), segment)
			content += segment.Content

			if err := os.WriteFile(fileName, []byte(content), 0644); err != nil {
				return totalSize, fmt.Errorf("写入文件失败 %s: %w", fileName, err)
			}

			totalSize += int64(len(content))
		}
	}

	return totalSize, nil
}

func generateFileName(prefix string, resultIdx, segIdx, totalResults, totalSegments int) string {
	if totalResults > 1 {
		if totalSegments > 1 {
			return fmt.Sprintf("%s_Project%d_Part%d_of_%d.md", prefix, resultIdx+1, segIdx+1, totalSegments)
		}
		return fmt.Sprintf("%s_Project%d.md", prefix, resultIdx+1)
	}

	if totalSegments > 1 {
		return fmt.Sprintf("%s_Part%d_of_%d.md", prefix, segIdx+1, totalSegments)
	}

	return fmt.Sprintf("%s.md", prefix)
}

func generateMetaComment(result *generator.Result, partNum, totalParts int, segment *generator.Segment) string {
	return fmt.Sprintf(`<!--
  Generated by PrintCode2LLM (ptlm)
  Project: %s
  Date: %s
  Part: %d of %d
  Files: %d-%d
-->

`, result.ProjectName, time.Now().Format(time.RFC3339), partNum, totalParts, segment.StartFile, segment.EndFile)
}